image: Visual Studio 2019

branches:
  only:
    - main

init:
  - git config --global core.autocrlf input

build_script:
  - dotnet --info
  - dotnet tool install --global coverlet.console --version 1.7.2
  - ps: .\build.ps1 -LinkSources -Verbosity Verbose

test: off

artifacts:
- path: 'packaging\octokit*.nupkg'
  name: OctokitPackages
